# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizard',
            name='wizard_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
