# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_wizard_wizard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='wizard_id',
        ),
    ]
