# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 18:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_remove_wizard_wizard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizard',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='wizard',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='wizard',
            name='last_name',
        ),
        migrations.AddField(
            model_name='wizard',
            name='json',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
