# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-17 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20160817_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wizard',
            old_name='json',
            new_name='data',
        ),
    ]
